content:
  - name: home
    label: Home Sections
    type: collection
    path: home
    filename: "slug"
    fields:
      - name: date
        label: Date
        type: date
        required: true

      - name: title
        label: Title
        type: string
        required: true

      - name: slug
        label: Slug
        type: string
        required: true

      - name: postImage
        label: Image
        type: image

      - name: order
        label: Order
        type: number

      - name: show
        label: Show
        type: boolean
        default: true

      - name: excerpt
        label: Excerpt
        type: text

      - name: section
        label: Section
        type: text

      - name: imageDirection
        label: Image Direction
        type: text

      - name: body
        label: Content
        type: string

  - name: posts
    label: Posts
    type: collection
    path: posts
    filename: "{{slug}}"
    fields:
      - name: date
        label: Date
        type: date
        required: true

      - name: title
        label: Title
        type: string
        required: true

      - name: slug
        label: Slug
        type: string
        required: true

      - name: postImage
        label: Image
        type: image

      - name: order
        label: Order
        type: number

      - name: show
        label: Show
        type: boolean
        default: true

      - name: excerpt
        label: Excerpt
        type: text

      - name: body
        label: Content
        type: string

media:
  - name: images
    label: Images
    input: images
    output: /images
